dotnet: Add dev-so to INSANE_SKIP
This fixes this error:

ERROR: dotnet-6.0.403-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package dotnet contains symlink .so '/usr/lib/libhostfxr.so' [dev-so]
ERROR: dotnet-6.0.403-r0 do_package_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: .../tmp-sicom-glibc/work/corei7-64-oe-linux/dotnet/6.0.403-r0/temp/log.do_package_qa.3465221
ERROR: Task (.../layers/meta-mono/recipes-mono/dotnet/dotnet_6.0.403.bb:do_package_qa) failed with exit code '1'

/usr/lib/libhostfxr.so is indeed a symlink to
../share/dotnet/host/fxr/6.0.11/libhostfxr.so which is
a real library file with no version encoded in its name.

There is no other .so symlink in this package in libdir, so
it's not a risk to use INSANE_SKIP = "dev-so".

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>