mono-4.xx: Remove --disable-static from EXTRA_OECONF
As of commit OE-Core:773c9e18071d71454473dd81aff911104a2e9bc6
EXTRA_OECONF is appended with the option --disable-static on
DISABLE_STATIC variable and this cause the error:
 __
/
| mono_boehm-main.o: In function `main':
| x86_64-linux/mono-native/4.4.0.122-r0/mono-4.4.0/mono/mini/main.c:51:
| undefined reference to `mono_build_date'
| collect2: error: ld returned 1 exit status
| Makefile:1390: recipe for target 'mono-boehm' failed
\__

There's a bug with this issue open here:
https://bugzilla.xamarin.com/show_bug.cgi?id=33081

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>