nuget: add DIRFILES to fix packaging failure issue
Error: Transaction check error:
  file /usr/lib/mono conflicts between attempted installs of nuget-3.5.0-r0.noarch and mono-libs-4.5-5.2.0.175-r0.i586

Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>