mono-5.xx: fix qa issue regarding rdepends
Fix QA issue complain about a missing runtime dependency:
"ERROR: mono-5.14.0.177-r0 do_package_qa: QA Issue:
/usr/bin/mono-find-requires contained in package mono-dev requires
/bin/bash, but no providers found in RDEPENDS_mono-dev? [file-rdeps]
ERROR: mono-5.14.0.177-r0 do_package_qa: QA run found fatal errors.
Please consider fixing them."

Signed-off-by: Kraag Gorim <kraaggorim@gmail.com>