mono-native: Modify build to eliminate dependency on on host system mscorlib.dll
Synopsis
========

mono-native builds fine with an Ubuntu 12.04 LTS host system, with or without mono installed from precise pangolin (i.e. Mono v2.x series).

If mono is upgraded to v3.x series using, say, ppa:directhex/monoxide then the build fails

@see http://stackoverflow.com/questions/13365158/installing-mono-3-x-3-0-x-and-or-3-2-x

Build messages includes a warning

../corlib/Mono/DataConverter.cs(759,25): warning CS0436: The type `Mono.DataConverter' conflicts with the imported type of same name'.
Ignoring the imported type definition
../../build/common/MonoTODOAttribute.cs(38,17): (Location of the symbol related to previous warning)
/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)

Then an error

MCS     [build] mscorlib.dll
Unhandled Exception:
System.TypeLoadException: Could not load type 'Mono.CSharp.CommandLineParser' from assembly 'basic, Version=3.2.8.0, Culture=neutral, PublicKeyToken=null'.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'Mono.CSharp.CommandLineParser' from assembly 'basic, Version=3.2.8.0, Culture=neutral, PublicKeyToken=null'.
make[8]: *** [../../class/lib/build/tmp/mscorlib.dll] Error 1

This appears related to Mono building its 'basic' profile. The makefile for this profile appears not to correctly set the path to the correct mscorlib.dll which this patch attempts to fix.

Testing
=======

With this patch in place a build of a qemux86 image succeeds with Mono 3.2.8 on the
host and the mono-helloworld recipe files can be executed successfully

Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>