dotnet: Revert to old pre-honister override syntax
Yocto changed the override syntax in Yocto honister (3.4). This was
introduced somehow in the dotnet recipe of the dunfell branch of
meta-mono.
Probably from https://github.com/intel-iot-devkit/meta-iot-cloud/blob/08d0c505097b889836315a4fe9b41acbb264be3f/recipes-devtools/dotnet/dotnet_5.0.300.bb

The error looks like this:
```
ERROR: ParseError at .../meta-mono/recipes-mono/dotnet/dotnet_5.0.300.bb:15: unparsed line: 'RDEPENDS:${PN} = "    icu     libgssapi-krb5     lttng-ust     zlib "'
```

Revert the changes back to the plain old Yocto override syntax.