Fix build on aarch64 builds
When building for aarch64 targets, I get build failures like:

ERROR: msbuild-native-16.6-r0 do_prepare_recipe_sysroot: Manifest
/workdir/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-mono.populate_sysroot
not found in imx8mn_ddr4_evk cortexa53 armv8a-crc armv8a aarch64
allarch x86_64_x86_64-nativesdk (variant '')?

The problem comes from the fact that some include files (i.e.:
mono-6.xx.inc) are used in both the mono and mono-native
variants. This seems to confuse the native class in some way. Ideally
we would have a single mono recipe declaring BBCLASSEXTEND = "native"
and we'd let bitbake generate the recipe variant.

See: https://docs.yoctoproject.org/ref-manual/variables.html?highlight=bbclassextend#term-BBCLASSEXTEND

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>