mono: add BBCLASSEXTEND=native to mono-6.xx.inc (#149)
* mono-base: append dependencies instead of using the hard assignment op

* Remove extra space

Not needed when using the += operator.

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>

* Fix build on aarch64 builds

When building for aarch64 targets, I get build failures like:

ERROR: msbuild-native-16.6-r0 do_prepare_recipe_sysroot: Manifest
/workdir/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-mono.populate_sysroot
not found in imx8mn_ddr4_evk cortexa53 armv8a-crc armv8a aarch64
allarch x86_64_x86_64-nativesdk (variant '')?

The problem comes from the fact that some include files (i.e.:
mono-6.xx.inc) are used in both the mono and mono-native
variants. This seems to confuse the native class in some way. Ideally
we would have a single mono recipe declaring BBCLASSEXTEND = "native"
and we'd let bitbake generate the recipe variant.

See: https://docs.yoctoproject.org/ref-manual/variables.html?highlight=bbclassextend#term-BBCLASSEXTEND

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>

* Fix build error of CI-Build:

Error:

 Problem 1: conflicting requests
  - nothing provides mono-gac needed by mono-6.12.0.161-r0.core2_64
  - nothing provides mono-libs-4.5 needed by mono-6.12.0.161-r0.core2_64

 Problem 2: package msbuild-16.6-r0.core2_64 requires mono, but none of the providers can be installed
  - conflicting requests
  - nothing provides mono-gac needed by mono-6.12.0.161-r0.core2_64
  - nothing provides mono-libs-4.5 needed by mono-6.12.0.161-r0.core2_64

 Problem 3: package mono-helloworld-1.2-r0.core2_64 requires mono, but none of the providers can be installed
  - conflicting requests
  - nothing provides mono-gac needed by mono-6.12.0.161-r0.core2_64
  - nothing provides mono-libs-4.5 needed by mono-6.12.0.161-r0.core2_64
(try to add '--skip-broken' to skip uninstallable packages)

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Co-authored-by: Georg Gebauer <georg.gebauer@zeiss.com>