msbuild-libhostfxr: Upgrade to 3.1.16
3.1.11 was hitting this compile error on Fedora 34 with GCC 11
as the host compiler:

| .../3.1.11-r0/git/src/corehost/cli/test/nativehost/host_context_test.cpp: In function ‘void {anonymous}::wait_for_signal_mock_execute_assembly()’:
| .../3.1.11-r0/git/src/corehost/cli/test/nativehost/host_context_test.cpp:436:31: error: ‘sleep_for’ is not a member of ‘std::this_thread’
|   436 |             std::this_thread::sleep_for(std::chrono::milliseconds(100));
|       |                               ^~~~~~~~~

This was fixed in commit a49e99c5517054c2fa8a6772ce028acf56dfc54c
("Fix build errors using GCC 11 (#46334) (#9136)") which is in 3.1.16

The current set of patches still apply to 3.1.16 but not newer.

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>