mono-5.xx: fix qa issue regarding rdepends
Fix QA issue regarding missing RDEPENDS for zlib:
"ERROR: mono-5.14.0.177-r0 do_package_qa: QA Issue:
/usr/lib/libMonoPosixHelper.so contained in package mono-libs requires
libz.so.1()(64bit), but no providers found in RDEPENDS_mono-libs?
[file-rdeps]
ERROR: mono-5.14.0.177-r0 do_package_qa: QA Issue: /usr/bin/mprof-report
contained in package mono requires libz.so.1()(64bit), but no providers
found in RDEPENDS_mono? [file-rdeps]"

Signed-off-by: Kraag Gorim <kraaggorim@gmail.com>